services:
  # Khoj Web Service
  - type: web
    name: khoj-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd src/interface/web && npm install && npm run build
      cd ../../../ && python src/khoj/manage.py collectstatic --noinput
    startCommand: gunicorn -c gunicorn-config.py src.khoj.main:app
    healthCheckPath: /api/health
    envVars:
      - key: KHOJ_DJANGO_SECRET_KEY
        generateValue: true
      - key: KHOJ_DEBUG
        value: "False"
      - key: KHOJ_ADMIN_EMAIL
        value: "admin@example.com"
      - key: KHOJ_ADMIN_PASSWORD
        generateValue: true
      - key: KHOJ_NO_HTTPS
        value: "False"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: NODE_VERSION
        value: "18"